#define CP866_OPTIMAL_PLANE_FOUND "Оптимальный план найден. Количество итераций = "
#define CP866_FUNCTION_UNDEFINED "Целевая функция не ограничена. Задача с данным условием не имеет решений."
#define CP866_NON_OPTIMAL_SOLUTION "Данная задача имеет решение, но оно не является оптимальным."
#define CP866_ENTER_FREE_MEMBER "Введите значение свободного члена для "
#define CP866_DASHGO_EQUATION "-го неравенства: "
#define CP866_ENTER_X "Введите коэффициент при X"
#define CP866_FOR " для "
#define CP866_ENTER_AMOUNT_OF_VARIABLES "Введите количество основных переменных задачи: "
#define CP866_ENTER_FUNCTION_DIRECTION "Введите направление целевой функции (max, min): "
#define CP866_WRONG_VALUE "Вы ввели недопустимое значение."
#define CP866_ENTER_X_FACTOR "Введите коэффициент целевой функции при X"
