#define CP866_OPTIMAL_PLANE_FOUND "Оптимальный план найден. Количество итераций = "
#define CP866_FUNCTION_UNDEFINED "Целевая функция не ограничена. Задача с данным условием не имеет решений."
#define CP866_NON_OPTIMAL_SOLUTION "Данная задача имеет решение, но оно не является оптимальным."
#define CP866_SELECT_INPUT_METHOD "Выберите метод ввода (вручную - 1, из файла - 2): "
#define CP866_ENTER_PATH_TO_FILE "Введите имя или путь к входному файлу: "
#define CP866_ENTER_FREE_MEMBER "Введите значение свободного члена для "
#define CP866_DASHGO_EQUATION "-го неравенства: "
#define CP866_ENTER_X "Введите коэффициент при X"
#define CP866_FOR " для "
#define CP866_ENTER_AMOUNT_OF_VARIABLES "Введите количество основных переменных задачи: "
#define CP866_ENTER_FUNCTION_DIRECTION "Введите направление целевой функции (max, min): "
#define CP866_UNDEFINED_ERROR "Возникла непредвиненная ошибка. попробуйте еще раз."
#define CP866_WRONG_VALUE "Вы ввели недопустимое значение."
#define CP866_CANNOT_ACCESS_FILE "Нет доступа к файлу!"
