default:
	c++ -Wall -ggdb Main.cpp Simplex.cpp InputData.cpp Matrix.cpp OutBase.cpp OutLinux.cpp -o Simplex
clean:
	rm -f Simplex
win32:
	cl.exe /EHsc /FeSimplex.exe Main.cpp Simplex.cpp InputData.cpp Matrix.cpp OutBase.cpp OutWin32.cpp
